### PR TITLE
partial Fix # 11 url query params

### PR DESCRIPTION
**Pull request by jacovinus**
- fix :  get parameters from query params
- fix: update query params when update parameters
- get URL with query params when "Share Link" button is pressed

### Usage
- Url params will be generated as you change the paramters inside UI

### Available params: 
**query:** the cLoki query , example: ```query=%7Btype%3D"clickhouse"%7D```
**limit:** the query Limit.  ```limit=100``` (default 1000)
**start:** query start ts nanosec ```start=```
**end:** query end ts nanosec   ```end=```
**step:** query step in sec or milisec ```step=5s```
**apiUrl:** the API URL to Make current request ```apiUrl=http:localhost:3100```

sample URL : ```http://localhost:3000/#query=%7Btype%3D"clickhouse"%7D&limit=1000&apiUrl=http%3A%2F%2Flocalhost%3A3100&step=100&start=1644594696494000&end=1644594996495000```

- Copy link button for sharing link with exact params

### CODE REVIEW

**Comment by Dletta** [comment]
Small Issue here:
- You can still use Hotkey (CTRL-ENTER) to submit an invalid query, even if 'Show Logs' button is inactive

**Comment by Dletta** [comment]
Another small item:
- When the page loads, it initially tries to load labels from the default, even if the user has changed the API URL

Error in console
```
XHR GET http://127.0.0.1:8080/loki/api/v1/labels 404
```
Even though API URL is set and labels are collected from
127.0.0.1:3100

It appears the /ValuesList.js useEffect() for querying labels is called once with default state, once with new state

**Comment by Dletta** [comment]
On loading defaults in updateStateFromQueryParams.js, apiUrl is not copied into the hash.

Looks like the culprit is on L#165, we set an empty string instead of the value we have already dispatched to store

**Comment by Dletta** [comment]
Initial State is now set by url parameters.
This fixes most issues with errors in console

Outstanding items:
* [ ]  Load Query after page loads (if the query is there and it's a valid query, execute query)
* [ ] Share Link button to add &submit=true
* [ ] '&submit=true' must work, or we get rid of it and do just point 1 on this list

**Comment by jacovinus** [comment]
> Small Issue here:
> 
> * You can still use Hotkey (CTRL-ENTER) to submit an invalid query, even if 'Show Logs' button is inactive

fixed with https://github.com/metrico/cloki-view/pull/25/commits/4253c9310baca152ee9906f4d344206c1de961d7

**Comment by jacovinus** [comment]
> Initial State is now set by url parameters. This fixes most issues with errors in console
> 
> Outstanding items:
> 
> * [x]   Load Query after page loads (if the query is there and it's a valid query, execute query)
> * [x]  Share Link button to add

fixed load logs on every query change with https://github.com/metrico/cloki-view/pull/25/commits/b44fa6f05726ff1f98371a437583b531b60cfbc7

**Comment by Dletta** [comment]
Tested Final Result, working well

**Pull request merged**
